# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Build Prod"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
  deploy:
    name: Deploy
    runs-on: [x64, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy container
        run: |
          echo "Deploy container"
          docker-compose down
          docker-compose rm -v
          docker system prune -a
          docker-compose build --no-cache
          docker-compose up -d
