name: "Build Demo"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    name: Deploy
    runs-on: [x64, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy container
        run: |
          echo "Deploy container"
          docker-compose down
          docker-compose rm -v
          docker system prune -a
          docker-compose build --no-cache
          docker-compose up -d
